kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: centos-stream9-desktop
  namespace: uat-infra-tools
  labels:
    workload.template.kubevirt.io/desktop: 'true'
    app.kubernetes.io/part-of: hyperconverged-cluster
    template.kubevirt.io/architecture: amd64
    template.kubevirt.io/version: v0.34.0
    app.kubernetes.io/version: 4.19.6
    template.kubevirt.io/type: vm
    vm.kubevirt.io/template: centos-stream9-desktop
    app.kubernetes.io/component: templating
    app.kubernetes.io/managed-by: ssp-operator
    flavor.template.kubevirt.io/medium: 'true'
    app.kubernetes.io/name: custom-templates
    vm.kubevirt.io/template.namespace: openshift
    os.template.kubevirt.io/centos-stream9: 'true'
  annotations:
    template.kubevirt.io/provider: ''
    name.os.template.kubevirt.io/centos-stream9: CentOS Stream 9 or higher
    template.kubevirt.io/provider-url: 'https://www.centos.org'
    template.kubevirt.io/containerdisks: |
      quay.io/containerdisks/centos-stream:9
    template.kubevirt.io/version: v1alpha1
    openshift.io/display-name: CentOS Stream 9 VM
    openshift.io/documentation-url: 'https://github.com/kubevirt/common-templates'
    template.kubevirt.io/images: |
      https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
    operator-sdk/primary-resource-type: SSP.ssp.kubevirt.io
    defaults.template.kubevirt.io/disk: rootdisk
    template.kubevirt.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.sockets
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.cpu.threads
      /objects[0].spec.template.spec.domain.memory.guest
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks
    template.openshift.io/bindable: 'false'
    openshift.kubevirt.io/pronounceable-suffix-for-name-expression: 'true'
    operator-sdk/primary-resource: openshift-cnv/ssp-kubevirt-hyperconverged
    tags: 'hidden,kubevirt,virtualmachine,linux,centosstream'
    template.kubevirt.io/provider-support-level: Community
    description: Template for CentOS Stream 9 VM or newer. A PVC with the CentOS Stream disk image must be available.
    openshift.io/support-url: 'https://github.com/kubevirt/common-templates/issues'
    iconClass: icon-centos
    openshift.io/provider-display-name: ''
objects:
  - apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      annotations:
        vm.kubevirt.io/validations: |
          [
            {
              "name": "minimal-required-memory",
              "path": "jsonpath::.spec.domain.memory.guest",
              "rule": "integer",
              "message": "This VM requires more memory.",
              "min": 1610612736
            }
          ]
      labels:
        app: '${NAME}'
        kubevirt.io/dynamic-credentials-support: 'true'
        vm.kubevirt.io/template: centos-stream9-desktop
        vm.kubevirt.io/template.revision: '1'
        vm.kubevirt.io/template.namespace: uat-infra-tools
      name: '${NAME}'
    spec:
      dataVolumeTemplates:
        - apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            name: '${NAME}'
          spec:
            sourceRef:
              kind: DataSource
              name: '${DATA_SOURCE_NAME}'
              namespace: '${DATA_SOURCE_NAMESPACE}'
            storage:
              resources:
                requests:
                  storage: 30Gi
      runStrategy: Halted
      template:
        metadata:
          annotations:
            vm.kubevirt.io/flavor: medium
            vm.kubevirt.io/os: centos-stream9
            vm.kubevirt.io/workload: desktop
          labels:
            kubevirt.io/domain: '${NAME}'
            kubevirt.io/size: medium
        spec:
          architecture: amd64
          domain:
            cpu:
              cores: 1
              sockets: 1
              threads: 1
            devices:
              disks:
                - disk:
                    bus: virtio
                  name: rootdisk
                - disk:
                    bus: virtio
                  name: cloudinitdisk
              inputs:
                - bus: virtio
                  name: tablet
                  type: tablet
              interfaces:
                - masquerade: {}
                  model: virtio
                  name: default
              rng: {}
            memory:
              guest: 4Gi
          networks:
            - name: default
              pod: {}
          terminationGracePeriodSeconds: 180
          volumes:
            - dataVolume:
                name: '${NAME}'
              name: rootdisk
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  user: centos
                  password: ${CLOUD_USER_PASSWORD}
                  chpasswd: { expire: False }
              name: cloudinitdisk
parameters:
  - name: NAME
    description: VM name
    generate: expression
    from: 'centos-stream9-[a-z0-9]{16}'
  - name: DATA_SOURCE_NAME
    description: Name of the DataSource to clone
    value: centos-stream9
  - name: DATA_SOURCE_NAMESPACE
    description: Namespace of the DataSource
    value: openshift-virtualization-os-images
  - name: CLOUD_USER_PASSWORD
    description: Randomized password for the cloud-init user centos
    generate: expression
    from: '[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}'

