kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: windows2k25
  namespace: uat-infra-tools
  labels:
    app.kubernetes.io/part-of: hyperconverged-cluster
    template.kubevirt.io/architecture: amd64
    template.kubevirt.io/version: v0.34.0
    app.kubernetes.io/version: 4.19.6
    template.kubevirt.io/type: vm
    os.template.kubevirt.io/win2k22: 'true'
    vm.kubevirt.io/template: windows2k22-vm-template
    app.kubernetes.io/component: templating
    app.kubernetes.io/managed-by: ssp-operator
    flavor.template.kubevirt.io/medium: 'true'
    app.kubernetes.io/name: custom-templates
    vm.kubevirt.io/template.namespace: uat-infra-tools
    workload.template.kubevirt.io/server: 'true'
  annotations:
    template.kubevirt.io/provider: ''
    template.kubevirt.io/provider-url: 'https://www.redhat.com'
    template.kubevirt.io/version: v1alpha1
    openshift.io/display-name: Microsoft Windows Server 2025 VM
    openshift.io/documentation-url: 'https://github.com/kubevirt/common-templates'
    name.os.template.kubevirt.io/win2k22: Microsoft Windows Server 2022
    operator-sdk/primary-resource-type: SSP.ssp.kubevirt.io
    defaults.template.kubevirt.io/disk: rootdisk
    template.kubevirt.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.memory.guest
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks
    template.openshift.io/bindable: 'false'
    openshift.kubevirt.io/pronounceable-suffix-for-name-expression: 'true'
    operator-sdk/primary-resource: openshift-cnv/ssp-kubevirt-hyperconverged
    tags: 'hidden,kubevirt,virtualmachine,windows'
    defaults.template.kubevirt.io/network: default
    template.kubevirt.io/provider-support-level: Full
    description: Template for Microsoft Windows Server 2022 VM. A PVC with the Windows disk image must be available.
    openshift.io/support-url: 'https://github.com/kubevirt/common-templates/issues'
    iconClass: icon-windows
    openshift.io/provider-display-name: ''
objects:
  - apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      annotations:
        vm.kubevirt.io/validations: |
          [
            {
              "name": "minimal-required-memory",
              "path": "jsonpath::.spec.domain.memory.guest",
              "rule": "integer",
              "message": "This VM requires more memory.",
              "min": 536870912
            }, {
              "name": "windows-virtio-bus",
              "path": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
              "valid": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
              "rule": "enum",
              "message": "virtio disk bus type has better performance, install virtio drivers in VM and change bus type",
              "values": ["virtio"],
              "justWarning": true
            }, {
              "name": "windows-disk-bus",
              "path": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
              "valid": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
              "rule": "enum",
              "message": "disk bus has to be either virtio or sata or scsi",
              "values": ["virtio", "sata", "scsi"]
            }, {
              "name": "windows-cd-bus",
              "path": "jsonpath::.spec.domain.devices.disks[*].cdrom.bus",
              "valid": "jsonpath::.spec.domain.devices.disks[*].cdrom.bus",
              "rule": "enum",
              "message": "cd bus has to be sata",
              "values": ["sata"]
            }
          ]
      labels:
        app: '${NAME}'
        vm.kubevirt.io/template: windows2k25
        vm.kubevirt.io/template.revision: '1'
        vm.kubevirt.io/template.namespace: uat-infra-tools
      name: '${NAME}'
      namespace: uat-infra-tools
    spec:
      dataVolumeTemplates:
        - metadata:
            name: 'dv-${NAME}-windows-vm-rootdisk-0vuey2'
          spec:
            source:
              pvc:
                name: windows-migration-1-pjlxd
                namespace: uat-infra-tools
            storage:
              resources:
                requests:
                  storage: 53Gi
              accessModes:
                - ReadWriteMany
              volumeMode: Filesystem
              storageClassName: nfs
      runStrategy: Halted
      template:
        metadata:
          annotations:
            vm.kubevirt.io/flavor: medium
            vm.kubevirt.io/os: windows2k22
            vm.kubevirt.io/workload: server
          labels:
            kubevirt.io/domain: '${NAME}'
            kubevirt.io/size: medium
        spec:
          architecture: amd64
          domain:
            clock:
              timer:
                hpet:
                  present: false
                hyperv: {}
                pit:
                  tickPolicy: delay
                rtc:
                  tickPolicy: catchup
              utc: {}
            cpu:
              cores: 1
              sockets: 1
              threads: 1
            devices:
              disks:
                - disk:
                    bus: sata
                  name: windows-vm-rootdisk
              inputs:
                - bus: usb
                  name: tablet
                  type: tablet
              interfaces:
                - masquerade: {}
                  model: e1000e
                  name: default
              tpm:
                persistent: true
            features:
              acpi: {}
              apic: {}
              hyperv:
                reenlightenment: {}
                ipi: {}
                synic: {}
                synictimer:
                  direct: {}
                spinlocks:
                  spinlocks: 8191
                reset: {}
                relaxed: {}
                vpindex: {}
                runtime: {}
                tlbflush: {}
                frequencies: {}
                vapic: {}
              smm: {}
            firmware:
              bootloader:
                efi:
                  persistent: true
                  secureBoot: true
            memory:
              guest: 4Gi
          networks:
            - name: default
              pod: {}
          terminationGracePeriodSeconds: 3600
          volumes:
            - dataVolume:
                name: 'dv-${NAME}-windows-vm-rootdisk-0vuey2'
              name: windows-vm-rootdisk
parameters:
  - name: NAME
    description: VM name
    generate: expression
    from: 'windows2022-[a-z0-9]{6}'
  - name: DATA_SOURCE_NAME
    description: Name of the DataSource to clone
    value: win2k22
  - name: DATA_SOURCE_NAMESPACE
    description: Namespace of the DataSource
    value: openshift-virtualization-os-images

